### ISSUE TITLE
CANNOT TURN OFF AUTOPLAY FUNCTION

### ISSUE THREAD

**Issue by levysantaana** [shiyiya/wordpress-plugin-oplayer#6]
I have set the autoplay to 0 via shortcode but the autoplay won't turn off. https://puncturerule.s3-tastewp.com/ Pleade check the first video link. Whenever I click the video link the video itself always playing in auto mode but when I refreshing the page it doesn't play in auto mode. Please help sir. Thank you in advance.

**Comment by shiyiya** [comment]
Fixed. Update it

**Comment by levysantaana** [comment]
Still the same sir. I used Chrome, Brave, Kiwi and other browsers.

**Comment by shiyiya** [comment]
I haven't seen any updates. https://puncturerule.s3-tastewp.com/

**Comment by levysantaana** [comment]
It's actually working now. All I did was clear the cache. Thank you. Btw, do you accept donation?

**Comment by shiyiya** [comment]
Thank you @levysantaana , but currently we are unable to open GitHub donations and can only make [private donations](https://github.com/shiyiya/oplayer?tab=readme-ov-file#support).
